name: p3_movie
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Allow any 3.x version
  flutter: ">=3.10.0"     # Minimum Flutter version

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0              # ^1.1.0 means >=1.1.0 <2.0.0
  cupertino_icons: ^1.0.6   # ^1.0.6 means >=1.0.6 <2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true